# Generated by Django 4.1.2 on 2024-03-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_challenge_end_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport_challenge',
            name='challenge_setter',
        ),
        migrations.RemoveField(
            model_name='transport_challenge',
            name='description',
        ),
    ]
