# Generated by Django 4.1.2 on 2024-02-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_user_id_user_setter_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='completeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('challenge_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.user')),
            ],
        ),
    ]
