# Generated by Django 4.1.2 on 2024-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_completechallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='garden',
            field=models.CharField(default='default_garden', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
