# Generated by Django 4.1.2 on 2024-03-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_transport_challenge_challenge_setter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_challenge',
            name='distance_covered',
            field=models.FloatField(default=0.0),
        ),
    ]
