# Generated by Django 4.1.2 on 2024-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_transport_challenge_distance_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gdpr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_challenges',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
