# Generated by Django 4.1.2 on 2024-02-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_user_garden_user_institution_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_challenges',
            field=models.CharField(default='', max_length=10),
        ),
    ]
