# Generated by Django 4.2.11 on 2024-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0006_remove_user_profile_image_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gdpr",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="completed_challenges",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
