# Generated by Django 4.1.2 on 2024-03-19 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_user_gdpr_alter_user_completed_challenges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTransportChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('distance', models.FloatField(default=0.0)),
                ('challenge_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.transport_challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
