# Generated by Django 4.1.2 on 2024-03-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_user_gdpr_alter_user_completed_challenges'),
        ('challenges', '0008_completetransportchallenge'),
    ]

    operations = [
    ]
